
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 
* DO NOT EDIT.
*
*  v (64-bit)
SW Build (by ) on 
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_AXI_GPIO_1_DEVICE_ID,
		XPAR_AXI_GPIO_1_BASEADDR,
		XPAR_AXI_GPIO_1_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_1_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_2_DEVICE_ID,
		XPAR_AXI_GPIO_2_BASEADDR,
		XPAR_AXI_GPIO_2_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_2_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_3_DEVICE_ID,
		XPAR_AXI_GPIO_3_BASEADDR,
		XPAR_AXI_GPIO_3_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_3_IS_DUAL
	}
};


