// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sha256_transform_16 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        block_0_read,
        block_1_read,
        block_2_read,
        block_3_read,
        block_4_read,
        block_5_read,
        block_6_read,
        block_7_read,
        ap_return
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] block_0_read;
input  [31:0] block_1_read;
input  [31:0] block_2_read;
input  [31:0] block_3_read;
input  [31:0] block_4_read;
input  [31:0] block_5_read;
input  [31:0] block_6_read;
input  [31:0] block_7_read;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] ap_return;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [6:0] i_1_fu_1143_p2;
reg   [6:0] i_1_reg_3034;
wire    ap_CS_fsm_state2;
wire   [31:0] tmp_30_fu_2189_p2;
reg   [31:0] tmp_30_reg_3048;
wire    ap_CS_fsm_state3;
wire   [31:0] tmp_31_fu_2199_p66;
reg   [31:0] tmp_31_reg_3053;
wire   [31:0] tmp17_fu_2473_p2;
reg   [31:0] tmp17_reg_3058;
wire   [31:0] tmp_46_fu_2497_p2;
reg   [31:0] tmp_46_reg_3063;
wire   [31:0] e_fu_2590_p2;
wire    ap_CS_fsm_state4;
wire   [31:0] a_fu_2601_p2;
reg   [31:0] c_reg_688;
reg   [31:0] b_reg_700;
reg   [6:0] i_reg_713;
reg   [31:0] d_reg_725;
reg   [31:0] d1_reg_738;
reg   [31:0] f_reg_751;
reg   [31:0] g_reg_763;
reg   [31:0] h_reg_776;
reg   [31:0] h1_reg_789;
reg   [31:0] ap_phi_mux_W_load_phi_phi_fu_805_p96;
wire   [0:0] exitcond_fu_1137_p2;
wire   [0:0] icmp_fu_1159_p2;
wire   [5:0] tmp_6_fu_1165_p1;
reg   [31:0] W_15_fu_384;
wire   [31:0] W_0_fu_1973_p18;
wire   [5:0] tmp_3_fu_2003_p1;
reg   [31:0] W_15_1_fu_388;
reg   [31:0] W_63_fu_392;
wire   [31:0] W_16_fu_1723_p2;
reg   [31:0] W_63_1_fu_396;
reg   [31:0] W_63_2_fu_400;
reg   [31:0] W_63_3_fu_404;
reg   [31:0] W_63_4_fu_408;
reg   [31:0] W_63_5_fu_412;
reg   [31:0] W_63_6_fu_416;
reg   [31:0] W_63_7_fu_420;
reg   [31:0] W_63_8_fu_424;
reg   [31:0] W_63_9_fu_428;
reg   [31:0] W_63_10_fu_432;
reg   [31:0] W_63_11_fu_436;
reg   [31:0] W_63_12_fu_440;
reg   [31:0] W_63_13_fu_444;
reg   [31:0] W_63_14_fu_448;
reg   [31:0] W_63_15_fu_452;
reg   [31:0] W_63_16_fu_456;
reg   [31:0] W_63_17_fu_460;
reg   [31:0] W_63_18_fu_464;
reg   [31:0] W_63_19_fu_468;
reg   [31:0] W_63_20_fu_472;
reg   [31:0] W_63_21_fu_476;
reg   [31:0] W_63_22_fu_480;
reg   [31:0] W_63_23_fu_484;
reg   [31:0] W_63_24_fu_488;
reg   [31:0] W_63_25_fu_492;
reg   [31:0] W_63_26_fu_496;
reg   [31:0] W_63_27_fu_500;
reg   [31:0] W_63_28_fu_504;
reg   [31:0] W_63_29_fu_508;
reg   [31:0] W_63_30_fu_512;
reg   [31:0] W_63_31_fu_516;
reg   [31:0] W_63_32_fu_520;
reg   [31:0] W_63_33_fu_524;
reg   [31:0] W_63_34_fu_528;
reg   [31:0] W_63_35_fu_532;
reg   [31:0] W_63_36_fu_536;
reg   [31:0] W_63_37_fu_540;
reg   [31:0] W_63_38_fu_544;
reg   [31:0] W_63_39_fu_548;
reg   [31:0] W_63_40_fu_552;
reg   [31:0] W_63_41_fu_556;
reg   [31:0] W_63_42_fu_560;
reg   [31:0] W_63_43_fu_564;
reg   [31:0] W_63_44_fu_568;
reg   [31:0] W_63_45_fu_572;
reg   [31:0] W_15_2_fu_576;
reg   [31:0] W_15_3_fu_580;
reg   [31:0] W_15_4_fu_584;
reg   [31:0] W_15_5_fu_588;
reg   [31:0] W_15_6_fu_592;
reg   [31:0] W_15_7_fu_596;
reg   [31:0] W_15_8_fu_600;
reg   [31:0] W_15_9_fu_604;
reg   [31:0] W_15_10_fu_608;
reg   [31:0] W_15_11_fu_612;
reg   [31:0] W_15_12_fu_616;
reg   [31:0] W_15_13_fu_620;
reg   [31:0] W_15_14_fu_624;
reg   [31:0] W_15_15_fu_628;
reg   [31:0] W_63_46_fu_632;
reg   [31:0] W_63_47_fu_636;
wire   [2:0] tmp_fu_1149_p4;
wire   [16:0] tmp_14_fu_1179_p1;
wire   [14:0] tmp_s_fu_1169_p4;
wire   [18:0] tmp_19_fu_1201_p1;
wire   [12:0] tmp_5_fu_1191_p4;
wire   [21:0] tmp_8_fu_1213_p4;
wire   [31:0] tmp_11_fu_1223_p1;
wire   [31:0] tmp_7_fu_1205_p3;
wire   [31:0] tmp8_fu_1227_p2;
wire   [31:0] tmp_4_fu_1183_p3;
wire   [31:0] W_load_2_phi_fu_1373_p66;
wire   [6:0] tmp_25_fu_1517_p1;
wire   [24:0] tmp_10_fu_1507_p4;
wire   [17:0] tmp_34_fu_1539_p1;
wire   [13:0] tmp_13_fu_1529_p4;
wire   [28:0] tmp_16_fu_1551_p4;
wire   [31:0] tmp_22_fu_1561_p1;
wire   [31:0] tmp_15_fu_1543_p3;
wire   [31:0] tmp9_fu_1565_p2;
wire   [31:0] tmp_12_fu_1521_p3;
wire   [31:0] tmp_17_fu_1571_p2;
wire   [31:0] W_load_1_phi_fu_1239_p66;
wire   [31:0] W_load_3_phi_fu_1577_p66;
wire   [31:0] tmp_9_fu_1233_p2;
wire   [31:0] tmp1_fu_1711_p2;
wire   [31:0] tmp2_fu_1717_p2;
wire   [3:0] W_0_fu_1973_p17;
wire   [5:0] tmp_37_fu_2109_p1;
wire   [25:0] tmp_18_fu_2099_p4;
wire   [10:0] tmp_40_fu_2131_p1;
wire   [20:0] tmp_21_fu_2121_p4;
wire   [24:0] tmp_47_fu_2153_p1;
wire   [6:0] tmp_24_fu_2143_p4;
wire   [31:0] tmp_20_fu_2113_p3;
wire   [31:0] tmp_23_fu_2135_p3;
wire   [31:0] tmp3_fu_2165_p2;
wire   [31:0] tmp_26_fu_2157_p3;
wire   [31:0] tmp_28_fu_2177_p2;
wire   [31:0] tmp_29_fu_2183_p2;
wire   [5:0] tmp_48_fu_2195_p1;
wire   [31:0] tmp_32_fu_2333_p66;
wire   [31:0] tmp18_fu_2467_p2;
wire   [31:0] tmp_27_fu_2171_p2;
wire   [31:0] tmp_43_fu_2479_p2;
wire   [31:0] tmp_44_fu_2485_p2;
wire   [31:0] tmp_45_fu_2491_p2;
wire   [31:0] tmp16_fu_2503_p2;
wire   [1:0] tmp_49_fu_2522_p1;
wire   [29:0] tmp_33_fu_2512_p4;
wire   [12:0] tmp_50_fu_2544_p1;
wire   [18:0] tmp_36_fu_2534_p4;
wire   [21:0] tmp_51_fu_2566_p1;
wire   [9:0] tmp_39_fu_2556_p4;
wire   [31:0] tmp_35_fu_2526_p3;
wire   [31:0] tmp_38_fu_2548_p3;
wire   [31:0] tmp19_fu_2578_p2;
wire   [31:0] tmp_41_fu_2570_p3;
wire   [31:0] t0_fu_2507_p2;
wire   [31:0] tmp20_fu_2596_p2;
wire   [31:0] tmp_42_fu_2584_p2;
wire   [31:0] tmp_2_fu_2087_p2;
reg   [31:0] ap_return_preg;
reg   [3:0] ap_NS_fsm;
reg    ap_condition_1570;
reg    ap_condition_666;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_return_preg = 32'd0;
end

scanhash_sha256d_bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 32 ),
    .din33_WIDTH( 32 ),
    .din34_WIDTH( 32 ),
    .din35_WIDTH( 32 ),
    .din36_WIDTH( 32 ),
    .din37_WIDTH( 32 ),
    .din38_WIDTH( 32 ),
    .din39_WIDTH( 32 ),
    .din40_WIDTH( 32 ),
    .din41_WIDTH( 32 ),
    .din42_WIDTH( 32 ),
    .din43_WIDTH( 32 ),
    .din44_WIDTH( 32 ),
    .din45_WIDTH( 32 ),
    .din46_WIDTH( 32 ),
    .din47_WIDTH( 32 ),
    .din48_WIDTH( 32 ),
    .din49_WIDTH( 32 ),
    .din50_WIDTH( 32 ),
    .din51_WIDTH( 32 ),
    .din52_WIDTH( 32 ),
    .din53_WIDTH( 32 ),
    .din54_WIDTH( 32 ),
    .din55_WIDTH( 32 ),
    .din56_WIDTH( 32 ),
    .din57_WIDTH( 32 ),
    .din58_WIDTH( 32 ),
    .din59_WIDTH( 32 ),
    .din60_WIDTH( 32 ),
    .din61_WIDTH( 32 ),
    .din62_WIDTH( 32 ),
    .din63_WIDTH( 32 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
scanhash_sha256d_bkb_U56(
    .din0(W_63_40_fu_552),
    .din1(W_63_40_fu_552),
    .din2(W_63_40_fu_552),
    .din3(W_63_40_fu_552),
    .din4(W_63_40_fu_552),
    .din5(W_63_40_fu_552),
    .din6(W_63_40_fu_552),
    .din7(W_63_40_fu_552),
    .din8(W_63_40_fu_552),
    .din9(W_63_40_fu_552),
    .din10(W_63_40_fu_552),
    .din11(W_63_40_fu_552),
    .din12(W_63_40_fu_552),
    .din13(W_63_40_fu_552),
    .din14(W_63_40_fu_552),
    .din15(W_63_40_fu_552),
    .din16(W_15_11_fu_612),
    .din17(W_15_12_fu_616),
    .din18(W_15_13_fu_620),
    .din19(W_15_14_fu_624),
    .din20(W_15_15_fu_628),
    .din21(W_15_fu_384),
    .din22(W_15_1_fu_388),
    .din23(W_63_fu_392),
    .din24(W_63_1_fu_396),
    .din25(W_63_2_fu_400),
    .din26(W_63_3_fu_404),
    .din27(W_63_4_fu_408),
    .din28(W_63_5_fu_412),
    .din29(W_63_6_fu_416),
    .din30(W_63_7_fu_420),
    .din31(W_63_8_fu_424),
    .din32(W_63_9_fu_428),
    .din33(W_63_10_fu_432),
    .din34(W_63_11_fu_436),
    .din35(W_63_12_fu_440),
    .din36(W_63_13_fu_444),
    .din37(W_63_14_fu_448),
    .din38(W_63_15_fu_452),
    .din39(W_63_16_fu_456),
    .din40(W_63_17_fu_460),
    .din41(W_63_18_fu_464),
    .din42(W_63_19_fu_468),
    .din43(W_63_20_fu_472),
    .din44(W_63_21_fu_476),
    .din45(W_63_22_fu_480),
    .din46(W_63_23_fu_484),
    .din47(W_63_24_fu_488),
    .din48(W_63_25_fu_492),
    .din49(W_63_26_fu_496),
    .din50(W_63_27_fu_500),
    .din51(W_63_28_fu_504),
    .din52(W_63_29_fu_508),
    .din53(W_63_30_fu_512),
    .din54(W_63_31_fu_516),
    .din55(W_63_32_fu_520),
    .din56(W_63_33_fu_524),
    .din57(W_63_34_fu_528),
    .din58(W_63_35_fu_532),
    .din59(W_63_36_fu_536),
    .din60(W_63_37_fu_540),
    .din61(W_63_38_fu_544),
    .din62(W_63_39_fu_548),
    .din63(W_63_40_fu_552),
    .din64(tmp_6_fu_1165_p1),
    .dout(W_load_1_phi_fu_1239_p66)
);

scanhash_sha256d_bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 32 ),
    .din33_WIDTH( 32 ),
    .din34_WIDTH( 32 ),
    .din35_WIDTH( 32 ),
    .din36_WIDTH( 32 ),
    .din37_WIDTH( 32 ),
    .din38_WIDTH( 32 ),
    .din39_WIDTH( 32 ),
    .din40_WIDTH( 32 ),
    .din41_WIDTH( 32 ),
    .din42_WIDTH( 32 ),
    .din43_WIDTH( 32 ),
    .din44_WIDTH( 32 ),
    .din45_WIDTH( 32 ),
    .din46_WIDTH( 32 ),
    .din47_WIDTH( 32 ),
    .din48_WIDTH( 32 ),
    .din49_WIDTH( 32 ),
    .din50_WIDTH( 32 ),
    .din51_WIDTH( 32 ),
    .din52_WIDTH( 32 ),
    .din53_WIDTH( 32 ),
    .din54_WIDTH( 32 ),
    .din55_WIDTH( 32 ),
    .din56_WIDTH( 32 ),
    .din57_WIDTH( 32 ),
    .din58_WIDTH( 32 ),
    .din59_WIDTH( 32 ),
    .din60_WIDTH( 32 ),
    .din61_WIDTH( 32 ),
    .din62_WIDTH( 32 ),
    .din63_WIDTH( 32 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
scanhash_sha256d_bkb_U57(
    .din0(W_63_32_fu_520),
    .din1(W_63_32_fu_520),
    .din2(W_63_32_fu_520),
    .din3(W_63_32_fu_520),
    .din4(W_63_32_fu_520),
    .din5(W_63_32_fu_520),
    .din6(W_63_32_fu_520),
    .din7(W_63_32_fu_520),
    .din8(W_63_32_fu_520),
    .din9(W_63_32_fu_520),
    .din10(W_63_32_fu_520),
    .din11(W_63_32_fu_520),
    .din12(W_63_32_fu_520),
    .din13(W_63_32_fu_520),
    .din14(W_63_32_fu_520),
    .din15(W_63_32_fu_520),
    .din16(W_15_3_fu_580),
    .din17(W_15_4_fu_584),
    .din18(W_15_5_fu_588),
    .din19(W_15_6_fu_592),
    .din20(W_15_7_fu_596),
    .din21(W_15_8_fu_600),
    .din22(W_15_9_fu_604),
    .din23(W_15_10_fu_608),
    .din24(W_15_11_fu_612),
    .din25(W_15_12_fu_616),
    .din26(W_15_13_fu_620),
    .din27(W_15_14_fu_624),
    .din28(W_15_15_fu_628),
    .din29(W_15_fu_384),
    .din30(W_15_1_fu_388),
    .din31(W_63_fu_392),
    .din32(W_63_1_fu_396),
    .din33(W_63_2_fu_400),
    .din34(W_63_3_fu_404),
    .din35(W_63_4_fu_408),
    .din36(W_63_5_fu_412),
    .din37(W_63_6_fu_416),
    .din38(W_63_7_fu_420),
    .din39(W_63_8_fu_424),
    .din40(W_63_9_fu_428),
    .din41(W_63_10_fu_432),
    .din42(W_63_11_fu_436),
    .din43(W_63_12_fu_440),
    .din44(W_63_13_fu_444),
    .din45(W_63_14_fu_448),
    .din46(W_63_15_fu_452),
    .din47(W_63_16_fu_456),
    .din48(W_63_17_fu_460),
    .din49(W_63_18_fu_464),
    .din50(W_63_19_fu_468),
    .din51(W_63_20_fu_472),
    .din52(W_63_21_fu_476),
    .din53(W_63_22_fu_480),
    .din54(W_63_23_fu_484),
    .din55(W_63_24_fu_488),
    .din56(W_63_25_fu_492),
    .din57(W_63_26_fu_496),
    .din58(W_63_27_fu_500),
    .din59(W_63_28_fu_504),
    .din60(W_63_29_fu_508),
    .din61(W_63_30_fu_512),
    .din62(W_63_31_fu_516),
    .din63(W_63_32_fu_520),
    .din64(tmp_6_fu_1165_p1),
    .dout(W_load_2_phi_fu_1373_p66)
);

scanhash_sha256d_bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 32 ),
    .din33_WIDTH( 32 ),
    .din34_WIDTH( 32 ),
    .din35_WIDTH( 32 ),
    .din36_WIDTH( 32 ),
    .din37_WIDTH( 32 ),
    .din38_WIDTH( 32 ),
    .din39_WIDTH( 32 ),
    .din40_WIDTH( 32 ),
    .din41_WIDTH( 32 ),
    .din42_WIDTH( 32 ),
    .din43_WIDTH( 32 ),
    .din44_WIDTH( 32 ),
    .din45_WIDTH( 32 ),
    .din46_WIDTH( 32 ),
    .din47_WIDTH( 32 ),
    .din48_WIDTH( 32 ),
    .din49_WIDTH( 32 ),
    .din50_WIDTH( 32 ),
    .din51_WIDTH( 32 ),
    .din52_WIDTH( 32 ),
    .din53_WIDTH( 32 ),
    .din54_WIDTH( 32 ),
    .din55_WIDTH( 32 ),
    .din56_WIDTH( 32 ),
    .din57_WIDTH( 32 ),
    .din58_WIDTH( 32 ),
    .din59_WIDTH( 32 ),
    .din60_WIDTH( 32 ),
    .din61_WIDTH( 32 ),
    .din62_WIDTH( 32 ),
    .din63_WIDTH( 32 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
scanhash_sha256d_bkb_U58(
    .din0(W_63_31_fu_516),
    .din1(W_63_31_fu_516),
    .din2(W_63_31_fu_516),
    .din3(W_63_31_fu_516),
    .din4(W_63_31_fu_516),
    .din5(W_63_31_fu_516),
    .din6(W_63_31_fu_516),
    .din7(W_63_31_fu_516),
    .din8(W_63_31_fu_516),
    .din9(W_63_31_fu_516),
    .din10(W_63_31_fu_516),
    .din11(W_63_31_fu_516),
    .din12(W_63_31_fu_516),
    .din13(W_63_31_fu_516),
    .din14(W_63_31_fu_516),
    .din15(W_63_31_fu_516),
    .din16(W_15_2_fu_576),
    .din17(W_15_3_fu_580),
    .din18(W_15_4_fu_584),
    .din19(W_15_5_fu_588),
    .din20(W_15_6_fu_592),
    .din21(W_15_7_fu_596),
    .din22(W_15_8_fu_600),
    .din23(W_15_9_fu_604),
    .din24(W_15_10_fu_608),
    .din25(W_15_11_fu_612),
    .din26(W_15_12_fu_616),
    .din27(W_15_13_fu_620),
    .din28(W_15_14_fu_624),
    .din29(W_15_15_fu_628),
    .din30(W_15_fu_384),
    .din31(W_15_1_fu_388),
    .din32(W_63_fu_392),
    .din33(W_63_1_fu_396),
    .din34(W_63_2_fu_400),
    .din35(W_63_3_fu_404),
    .din36(W_63_4_fu_408),
    .din37(W_63_5_fu_412),
    .din38(W_63_6_fu_416),
    .din39(W_63_7_fu_420),
    .din40(W_63_8_fu_424),
    .din41(W_63_9_fu_428),
    .din42(W_63_10_fu_432),
    .din43(W_63_11_fu_436),
    .din44(W_63_12_fu_440),
    .din45(W_63_13_fu_444),
    .din46(W_63_14_fu_448),
    .din47(W_63_15_fu_452),
    .din48(W_63_16_fu_456),
    .din49(W_63_17_fu_460),
    .din50(W_63_18_fu_464),
    .din51(W_63_19_fu_468),
    .din52(W_63_20_fu_472),
    .din53(W_63_21_fu_476),
    .din54(W_63_22_fu_480),
    .din55(W_63_23_fu_484),
    .din56(W_63_24_fu_488),
    .din57(W_63_25_fu_492),
    .din58(W_63_26_fu_496),
    .din59(W_63_27_fu_500),
    .din60(W_63_28_fu_504),
    .din61(W_63_29_fu_508),
    .din62(W_63_30_fu_512),
    .din63(W_63_31_fu_516),
    .din64(tmp_6_fu_1165_p1),
    .dout(W_load_3_phi_fu_1577_p66)
);

scanhash_sha256d_cud_x #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
scanhash_sha256d_cud_x_U59(
    .din0(block_0_read),
    .din1(block_1_read),
    .din2(block_2_read),
    .din3(block_3_read),
    .din4(block_4_read),
    .din5(block_5_read),
    .din6(block_6_read),
    .din7(block_7_read),
    .din8(32'd2147483648),
    .din9(32'd0),
    .din10(32'd0),
    .din11(32'd0),
    .din12(32'd0),
    .din13(32'd0),
    .din14(32'd0),
    .din15(32'd256),
    .din16(W_0_fu_1973_p17),
    .dout(W_0_fu_1973_p18)
);

scanhash_sha256d_bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 32 ),
    .din33_WIDTH( 32 ),
    .din34_WIDTH( 32 ),
    .din35_WIDTH( 32 ),
    .din36_WIDTH( 32 ),
    .din37_WIDTH( 32 ),
    .din38_WIDTH( 32 ),
    .din39_WIDTH( 32 ),
    .din40_WIDTH( 32 ),
    .din41_WIDTH( 32 ),
    .din42_WIDTH( 32 ),
    .din43_WIDTH( 32 ),
    .din44_WIDTH( 32 ),
    .din45_WIDTH( 32 ),
    .din46_WIDTH( 32 ),
    .din47_WIDTH( 32 ),
    .din48_WIDTH( 32 ),
    .din49_WIDTH( 32 ),
    .din50_WIDTH( 32 ),
    .din51_WIDTH( 32 ),
    .din52_WIDTH( 32 ),
    .din53_WIDTH( 32 ),
    .din54_WIDTH( 32 ),
    .din55_WIDTH( 32 ),
    .din56_WIDTH( 32 ),
    .din57_WIDTH( 32 ),
    .din58_WIDTH( 32 ),
    .din59_WIDTH( 32 ),
    .din60_WIDTH( 32 ),
    .din61_WIDTH( 32 ),
    .din62_WIDTH( 32 ),
    .din63_WIDTH( 32 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
scanhash_sha256d_bkb_U60(
    .din0(32'd1116352408),
    .din1(32'd1899447441),
    .din2(32'd3049323471),
    .din3(32'd3921009573),
    .din4(32'd961987163),
    .din5(32'd1508970993),
    .din6(32'd2453635748),
    .din7(32'd2870763221),
    .din8(32'd3624381080),
    .din9(32'd310598401),
    .din10(32'd607225278),
    .din11(32'd1426881987),
    .din12(32'd1925078388),
    .din13(32'd2162078206),
    .din14(32'd2614888103),
    .din15(32'd3248222580),
    .din16(32'd3835390401),
    .din17(32'd4022224774),
    .din18(32'd264347078),
    .din19(32'd604807628),
    .din20(32'd770255983),
    .din21(32'd1249150122),
    .din22(32'd1555081692),
    .din23(32'd1996064986),
    .din24(32'd2554220882),
    .din25(32'd2821834349),
    .din26(32'd2952996808),
    .din27(32'd3210313671),
    .din28(32'd3336571891),
    .din29(32'd3584528711),
    .din30(32'd113926993),
    .din31(32'd338241895),
    .din32(32'd666307205),
    .din33(32'd773529912),
    .din34(32'd1294757372),
    .din35(32'd1396182291),
    .din36(32'd1695183700),
    .din37(32'd1986661051),
    .din38(32'd2177026350),
    .din39(32'd2456956037),
    .din40(32'd2730485921),
    .din41(32'd2820302411),
    .din42(32'd3259730800),
    .din43(32'd3345764771),
    .din44(32'd3516065817),
    .din45(32'd3600352804),
    .din46(32'd4094571909),
    .din47(32'd275423344),
    .din48(32'd430227734),
    .din49(32'd506948616),
    .din50(32'd659060556),
    .din51(32'd883997877),
    .din52(32'd958139571),
    .din53(32'd1322822218),
    .din54(32'd1537002063),
    .din55(32'd1747873779),
    .din56(32'd1955562222),
    .din57(32'd2024104815),
    .din58(32'd2227730452),
    .din59(32'd2361852424),
    .din60(32'd2428436474),
    .din61(32'd2756734187),
    .din62(32'd3204031479),
    .din63(32'd3329325298),
    .din64(tmp_48_fu_2195_p1),
    .dout(tmp_31_fu_2199_p66)
);

scanhash_sha256d_bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 32 ),
    .din33_WIDTH( 32 ),
    .din34_WIDTH( 32 ),
    .din35_WIDTH( 32 ),
    .din36_WIDTH( 32 ),
    .din37_WIDTH( 32 ),
    .din38_WIDTH( 32 ),
    .din39_WIDTH( 32 ),
    .din40_WIDTH( 32 ),
    .din41_WIDTH( 32 ),
    .din42_WIDTH( 32 ),
    .din43_WIDTH( 32 ),
    .din44_WIDTH( 32 ),
    .din45_WIDTH( 32 ),
    .din46_WIDTH( 32 ),
    .din47_WIDTH( 32 ),
    .din48_WIDTH( 32 ),
    .din49_WIDTH( 32 ),
    .din50_WIDTH( 32 ),
    .din51_WIDTH( 32 ),
    .din52_WIDTH( 32 ),
    .din53_WIDTH( 32 ),
    .din54_WIDTH( 32 ),
    .din55_WIDTH( 32 ),
    .din56_WIDTH( 32 ),
    .din57_WIDTH( 32 ),
    .din58_WIDTH( 32 ),
    .din59_WIDTH( 32 ),
    .din60_WIDTH( 32 ),
    .din61_WIDTH( 32 ),
    .din62_WIDTH( 32 ),
    .din63_WIDTH( 32 ),
    .din64_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
scanhash_sha256d_bkb_U61(
    .din0(W_15_2_fu_576),
    .din1(W_15_3_fu_580),
    .din2(W_15_4_fu_584),
    .din3(W_15_5_fu_588),
    .din4(W_15_6_fu_592),
    .din5(W_15_7_fu_596),
    .din6(W_15_8_fu_600),
    .din7(W_15_9_fu_604),
    .din8(W_15_10_fu_608),
    .din9(W_15_11_fu_612),
    .din10(W_15_12_fu_616),
    .din11(W_15_13_fu_620),
    .din12(W_15_14_fu_624),
    .din13(W_15_15_fu_628),
    .din14(W_15_fu_384),
    .din15(W_15_1_fu_388),
    .din16(W_63_fu_392),
    .din17(W_63_1_fu_396),
    .din18(W_63_2_fu_400),
    .din19(W_63_3_fu_404),
    .din20(W_63_4_fu_408),
    .din21(W_63_5_fu_412),
    .din22(W_63_6_fu_416),
    .din23(W_63_7_fu_420),
    .din24(W_63_8_fu_424),
    .din25(W_63_9_fu_428),
    .din26(W_63_10_fu_432),
    .din27(W_63_11_fu_436),
    .din28(W_63_12_fu_440),
    .din29(W_63_13_fu_444),
    .din30(W_63_14_fu_448),
    .din31(W_63_15_fu_452),
    .din32(W_63_16_fu_456),
    .din33(W_63_17_fu_460),
    .din34(W_63_18_fu_464),
    .din35(W_63_19_fu_468),
    .din36(W_63_20_fu_472),
    .din37(W_63_21_fu_476),
    .din38(W_63_22_fu_480),
    .din39(W_63_23_fu_484),
    .din40(W_63_24_fu_488),
    .din41(W_63_25_fu_492),
    .din42(W_63_26_fu_496),
    .din43(W_63_27_fu_500),
    .din44(W_63_28_fu_504),
    .din45(W_63_29_fu_508),
    .din46(W_63_30_fu_512),
    .din47(W_63_31_fu_516),
    .din48(W_63_32_fu_520),
    .din49(W_63_33_fu_524),
    .din50(W_63_34_fu_528),
    .din51(W_63_35_fu_532),
    .din52(W_63_36_fu_536),
    .din53(W_63_37_fu_540),
    .din54(W_63_38_fu_544),
    .din55(W_63_39_fu_548),
    .din56(W_63_40_fu_552),
    .din57(W_63_41_fu_556),
    .din58(W_63_42_fu_560),
    .din59(W_63_43_fu_564),
    .din60(W_63_44_fu_568),
    .din61(W_63_45_fu_572),
    .din62(W_63_46_fu_632),
    .din63(W_63_47_fu_636),
    .din64(tmp_48_fu_2195_p1),
    .dout(tmp_32_fu_2333_p66)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 32'd0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (exitcond_fu_1137_p2 == 1'd1))) begin
            ap_return_preg <= tmp_2_fu_2087_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        b_reg_700 <= a_fu_2601_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        b_reg_700 <= 32'd1779033703;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        c_reg_688 <= b_reg_700;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        c_reg_688 <= 32'd3144134277;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        d1_reg_738 <= d_reg_725;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        d1_reg_738 <= 32'd2773480762;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        d_reg_725 <= c_reg_688;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        d_reg_725 <= 32'd1013904242;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        f_reg_751 <= e_fu_2590_p2;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        f_reg_751 <= 32'd1359893119;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        g_reg_763 <= f_reg_751;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        g_reg_763 <= 32'd2600822924;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        h1_reg_789 <= h_reg_776;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        h1_reg_789 <= 32'd1541459225;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        h_reg_776 <= g_reg_763;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        h_reg_776 <= 32'd528734635;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        i_reg_713 <= i_1_reg_3034;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_713 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_fu_2003_p1 == 6'd8) & (1'b1 == ap_CS_fsm_state2) & (icmp_fu_1159_p2 == 1'd1) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_15_10_fu_608 <= W_0_fu_1973_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_fu_2003_p1 == 6'd9) & (1'b1 == ap_CS_fsm_state2) & (icmp_fu_1159_p2 == 1'd1) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_15_11_fu_612 <= W_0_fu_1973_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_fu_2003_p1 == 6'd10) & (1'b1 == ap_CS_fsm_state2) & (icmp_fu_1159_p2 == 1'd1) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_15_12_fu_616 <= W_0_fu_1973_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_fu_2003_p1 == 6'd11) & (1'b1 == ap_CS_fsm_state2) & (icmp_fu_1159_p2 == 1'd1) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_15_13_fu_620 <= W_0_fu_1973_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_fu_2003_p1 == 6'd12) & (1'b1 == ap_CS_fsm_state2) & (icmp_fu_1159_p2 == 1'd1) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_15_14_fu_624 <= W_0_fu_1973_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_fu_2003_p1 == 6'd13) & (1'b1 == ap_CS_fsm_state2) & (icmp_fu_1159_p2 == 1'd1) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_15_15_fu_628 <= W_0_fu_1973_p18;
    end
end

always @ (posedge ap_clk) begin
    if ((~(tmp_3_fu_2003_p1 == 6'd13) & ~(tmp_3_fu_2003_p1 == 6'd12) & ~(tmp_3_fu_2003_p1 == 6'd11) & ~(tmp_3_fu_2003_p1 == 6'd10) & ~(tmp_3_fu_2003_p1 == 6'd9) & ~(tmp_3_fu_2003_p1 == 6'd8) & ~(tmp_3_fu_2003_p1 == 6'd7) & ~(tmp_3_fu_2003_p1 == 6'd6) & ~(tmp_3_fu_2003_p1 == 6'd5) & ~(tmp_3_fu_2003_p1 == 6'd4) & ~(tmp_3_fu_2003_p1 == 6'd3) & ~(tmp_3_fu_2003_p1 == 6'd2) & ~(tmp_3_fu_2003_p1 == 6'd1) & ~(tmp_3_fu_2003_p1 == 6'd0) & ~(tmp_3_fu_2003_p1 == 6'd14) & (1'b1 == ap_CS_fsm_state2) & (icmp_fu_1159_p2 == 1'd1) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_15_1_fu_388 <= W_0_fu_1973_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_fu_2003_p1 == 6'd0) & (1'b1 == ap_CS_fsm_state2) & (icmp_fu_1159_p2 == 1'd1) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_15_2_fu_576 <= W_0_fu_1973_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_fu_2003_p1 == 6'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_fu_1159_p2 == 1'd1) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_15_3_fu_580 <= W_0_fu_1973_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_fu_2003_p1 == 6'd2) & (1'b1 == ap_CS_fsm_state2) & (icmp_fu_1159_p2 == 1'd1) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_15_4_fu_584 <= W_0_fu_1973_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_fu_2003_p1 == 6'd3) & (1'b1 == ap_CS_fsm_state2) & (icmp_fu_1159_p2 == 1'd1) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_15_5_fu_588 <= W_0_fu_1973_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_fu_2003_p1 == 6'd4) & (1'b1 == ap_CS_fsm_state2) & (icmp_fu_1159_p2 == 1'd1) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_15_6_fu_592 <= W_0_fu_1973_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_fu_2003_p1 == 6'd5) & (1'b1 == ap_CS_fsm_state2) & (icmp_fu_1159_p2 == 1'd1) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_15_7_fu_596 <= W_0_fu_1973_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_fu_2003_p1 == 6'd6) & (1'b1 == ap_CS_fsm_state2) & (icmp_fu_1159_p2 == 1'd1) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_15_8_fu_600 <= W_0_fu_1973_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_fu_2003_p1 == 6'd7) & (1'b1 == ap_CS_fsm_state2) & (icmp_fu_1159_p2 == 1'd1) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_15_9_fu_604 <= W_0_fu_1973_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_3_fu_2003_p1 == 6'd14) & (1'b1 == ap_CS_fsm_state2) & (icmp_fu_1159_p2 == 1'd1) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_15_fu_384 <= W_0_fu_1973_p18;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd26) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_10_fu_432 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd27) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_11_fu_436 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd28) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_12_fu_440 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd29) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_13_fu_444 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd30) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_14_fu_448 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd31) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_15_fu_452 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd32) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_16_fu_456 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd33) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_17_fu_460 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd34) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_18_fu_464 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd35) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_19_fu_468 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd17) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_1_fu_396 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd36) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_20_fu_472 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd37) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_21_fu_476 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd38) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_22_fu_480 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd39) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_23_fu_484 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd40) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_24_fu_488 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd41) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_25_fu_492 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd42) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_26_fu_496 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd43) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_27_fu_500 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd44) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_28_fu_504 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd45) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_29_fu_508 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd18) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_2_fu_400 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd46) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_30_fu_512 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd47) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_31_fu_516 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd48) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_32_fu_520 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd49) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_33_fu_524 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd50) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_34_fu_528 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd51) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_35_fu_532 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd52) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_36_fu_536 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd53) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_37_fu_540 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd54) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_38_fu_544 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd55) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_39_fu_548 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd19) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_3_fu_404 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd56) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_40_fu_552 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd57) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_41_fu_556 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd58) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_42_fu_560 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd59) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_43_fu_564 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd60) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_44_fu_568 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd61) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_45_fu_572 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd62) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_46_fu_632 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(tmp_6_fu_1165_p1 == 6'd16) & ~(tmp_6_fu_1165_p1 == 6'd62) & ~(tmp_6_fu_1165_p1 == 6'd61) & ~(tmp_6_fu_1165_p1 == 6'd60) & ~(tmp_6_fu_1165_p1 == 6'd59) & ~(tmp_6_fu_1165_p1 == 6'd58) & ~(tmp_6_fu_1165_p1 == 6'd57) & ~(tmp_6_fu_1165_p1 == 6'd56) & ~(tmp_6_fu_1165_p1 == 6'd55) & ~(tmp_6_fu_1165_p1 == 6'd54) & ~(tmp_6_fu_1165_p1 == 6'd53) & ~(tmp_6_fu_1165_p1 == 6'd52) & ~(tmp_6_fu_1165_p1 == 6'd51) & ~(tmp_6_fu_1165_p1 == 6'd50) & ~(tmp_6_fu_1165_p1 == 6'd49) & ~(tmp_6_fu_1165_p1 == 6'd48) & ~(tmp_6_fu_1165_p1 == 6'd47) & ~(tmp_6_fu_1165_p1 == 6'd46) & ~(tmp_6_fu_1165_p1 == 6'd45) & ~(tmp_6_fu_1165_p1 == 6'd44) & ~(tmp_6_fu_1165_p1 == 6'd43) & ~(tmp_6_fu_1165_p1 == 6'd42) & ~(tmp_6_fu_1165_p1 == 6'd41) & ~(tmp_6_fu_1165_p1 == 6'd40) & ~(tmp_6_fu_1165_p1 == 6'd39) & ~(tmp_6_fu_1165_p1 == 6'd38) & ~(tmp_6_fu_1165_p1 == 6'd37) & ~(tmp_6_fu_1165_p1 == 6'd36) & ~(tmp_6_fu_1165_p1 == 6'd35) & ~(tmp_6_fu_1165_p1 == 6'd34) & ~(tmp_6_fu_1165_p1 == 6'd33) & ~(tmp_6_fu_1165_p1 == 6'd32) & ~(tmp_6_fu_1165_p1 == 6'd31) & ~(tmp_6_fu_1165_p1 == 6'd30) & ~(tmp_6_fu_1165_p1 == 6'd29) & ~(tmp_6_fu_1165_p1 == 6'd28) & ~(tmp_6_fu_1165_p1 == 6'd27) & ~(tmp_6_fu_1165_p1 == 6'd26) & ~(tmp_6_fu_1165_p1 == 6'd25) & ~(tmp_6_fu_1165_p1 == 6'd24) & ~(tmp_6_fu_1165_p1 == 6'd23) & ~(tmp_6_fu_1165_p1 == 6'd22) & ~(tmp_6_fu_1165_p1 == 6'd21) & ~(tmp_6_fu_1165_p1 == 6'd20) & ~(tmp_6_fu_1165_p1 == 6'd19) & ~(tmp_6_fu_1165_p1 == 6'd18) & ~(tmp_6_fu_1165_p1 == 6'd17) & (1'b1 == ap_CS_fsm_state2) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_47_fu_636 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd20) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_4_fu_408 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd21) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_5_fu_412 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd22) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_6_fu_416 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd23) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_7_fu_420 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd24) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_8_fu_424 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd25) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_9_fu_428 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (tmp_6_fu_1165_p1 == 6'd16) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0))) begin
        W_63_fu_392 <= W_16_fu_1723_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_1_reg_3034 <= i_1_fu_1143_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp17_reg_3058 <= tmp17_fu_2473_p2;
        tmp_30_reg_3048 <= tmp_30_fu_2189_p2;
        tmp_31_reg_3053 <= tmp_31_fu_2199_p66;
        tmp_46_reg_3063 <= tmp_46_fu_2497_p2;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (exitcond_fu_1137_p2 == 1'd1)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_666)) begin
        if ((tmp_6_fu_1165_p1 == 6'd16)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_15_fu_384;
        end else if ((1'b1 == ap_condition_1570)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_45_fu_572;
        end else if ((tmp_6_fu_1165_p1 == 6'd62)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_44_fu_568;
        end else if ((tmp_6_fu_1165_p1 == 6'd61)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_43_fu_564;
        end else if ((tmp_6_fu_1165_p1 == 6'd60)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_42_fu_560;
        end else if ((tmp_6_fu_1165_p1 == 6'd59)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_41_fu_556;
        end else if ((tmp_6_fu_1165_p1 == 6'd58)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_40_fu_552;
        end else if ((tmp_6_fu_1165_p1 == 6'd57)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_39_fu_548;
        end else if ((tmp_6_fu_1165_p1 == 6'd56)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_38_fu_544;
        end else if ((tmp_6_fu_1165_p1 == 6'd55)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_37_fu_540;
        end else if ((tmp_6_fu_1165_p1 == 6'd54)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_36_fu_536;
        end else if ((tmp_6_fu_1165_p1 == 6'd53)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_35_fu_532;
        end else if ((tmp_6_fu_1165_p1 == 6'd52)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_34_fu_528;
        end else if ((tmp_6_fu_1165_p1 == 6'd51)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_33_fu_524;
        end else if ((tmp_6_fu_1165_p1 == 6'd50)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_32_fu_520;
        end else if ((tmp_6_fu_1165_p1 == 6'd49)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_31_fu_516;
        end else if ((tmp_6_fu_1165_p1 == 6'd48)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_30_fu_512;
        end else if ((tmp_6_fu_1165_p1 == 6'd47)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_29_fu_508;
        end else if ((tmp_6_fu_1165_p1 == 6'd46)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_28_fu_504;
        end else if ((tmp_6_fu_1165_p1 == 6'd45)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_27_fu_500;
        end else if ((tmp_6_fu_1165_p1 == 6'd44)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_26_fu_496;
        end else if ((tmp_6_fu_1165_p1 == 6'd43)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_25_fu_492;
        end else if ((tmp_6_fu_1165_p1 == 6'd42)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_24_fu_488;
        end else if ((tmp_6_fu_1165_p1 == 6'd41)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_23_fu_484;
        end else if ((tmp_6_fu_1165_p1 == 6'd40)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_22_fu_480;
        end else if ((tmp_6_fu_1165_p1 == 6'd39)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_21_fu_476;
        end else if ((tmp_6_fu_1165_p1 == 6'd38)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_20_fu_472;
        end else if ((tmp_6_fu_1165_p1 == 6'd37)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_19_fu_468;
        end else if ((tmp_6_fu_1165_p1 == 6'd36)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_18_fu_464;
        end else if ((tmp_6_fu_1165_p1 == 6'd35)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_17_fu_460;
        end else if ((tmp_6_fu_1165_p1 == 6'd34)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_16_fu_456;
        end else if ((tmp_6_fu_1165_p1 == 6'd33)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_15_fu_452;
        end else if ((tmp_6_fu_1165_p1 == 6'd32)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_14_fu_448;
        end else if ((tmp_6_fu_1165_p1 == 6'd31)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_13_fu_444;
        end else if ((tmp_6_fu_1165_p1 == 6'd30)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_12_fu_440;
        end else if ((tmp_6_fu_1165_p1 == 6'd29)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_11_fu_436;
        end else if ((tmp_6_fu_1165_p1 == 6'd28)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_10_fu_432;
        end else if ((tmp_6_fu_1165_p1 == 6'd27)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_9_fu_428;
        end else if ((tmp_6_fu_1165_p1 == 6'd26)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_8_fu_424;
        end else if ((tmp_6_fu_1165_p1 == 6'd25)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_7_fu_420;
        end else if ((tmp_6_fu_1165_p1 == 6'd24)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_6_fu_416;
        end else if ((tmp_6_fu_1165_p1 == 6'd23)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_5_fu_412;
        end else if ((tmp_6_fu_1165_p1 == 6'd22)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_4_fu_408;
        end else if ((tmp_6_fu_1165_p1 == 6'd21)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_3_fu_404;
        end else if ((tmp_6_fu_1165_p1 == 6'd20)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_2_fu_400;
        end else if ((tmp_6_fu_1165_p1 == 6'd19)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_1_fu_396;
        end else if ((tmp_6_fu_1165_p1 == 6'd18)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_63_fu_392;
        end else if ((tmp_6_fu_1165_p1 == 6'd17)) begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = W_15_1_fu_388;
        end else begin
            ap_phi_mux_W_load_phi_phi_fu_805_p96 = 'bx;
        end
    end else begin
        ap_phi_mux_W_load_phi_phi_fu_805_p96 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond_fu_1137_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond_fu_1137_p2 == 1'd1))) begin
        ap_return = tmp_2_fu_2087_p2;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (exitcond_fu_1137_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign W_0_fu_1973_p17 = i_reg_713[3:0];

assign W_16_fu_1723_p2 = (tmp1_fu_1711_p2 + tmp2_fu_1717_p2);

assign a_fu_2601_p2 = (tmp20_fu_2596_p2 + tmp_42_fu_2584_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_condition_1570 = (~(tmp_6_fu_1165_p1 == 6'd16) & ~(tmp_6_fu_1165_p1 == 6'd62) & ~(tmp_6_fu_1165_p1 == 6'd61) & ~(tmp_6_fu_1165_p1 == 6'd60) & ~(tmp_6_fu_1165_p1 == 6'd59) & ~(tmp_6_fu_1165_p1 == 6'd58) & ~(tmp_6_fu_1165_p1 == 6'd57) & ~(tmp_6_fu_1165_p1 == 6'd56) & ~(tmp_6_fu_1165_p1 == 6'd55) & ~(tmp_6_fu_1165_p1 == 6'd54) & ~(tmp_6_fu_1165_p1 == 6'd53) & ~(tmp_6_fu_1165_p1 == 6'd52) & ~(tmp_6_fu_1165_p1 == 6'd51) & ~(tmp_6_fu_1165_p1 == 6'd50) & ~(tmp_6_fu_1165_p1 == 6'd49) & ~(tmp_6_fu_1165_p1 == 6'd48) & ~(tmp_6_fu_1165_p1 == 6'd47) & ~(tmp_6_fu_1165_p1 == 6'd46) & ~(tmp_6_fu_1165_p1 == 6'd45) & ~(tmp_6_fu_1165_p1 == 6'd44) & ~(tmp_6_fu_1165_p1 == 6'd43) & ~(tmp_6_fu_1165_p1 == 6'd42) & ~(tmp_6_fu_1165_p1 == 6'd41) & ~(tmp_6_fu_1165_p1 == 6'd40) & ~(tmp_6_fu_1165_p1 == 6'd39) & ~(tmp_6_fu_1165_p1 == 6'd38) & ~(tmp_6_fu_1165_p1 == 6'd37) & ~(tmp_6_fu_1165_p1 == 6'd36) & ~(tmp_6_fu_1165_p1 == 6'd35) & ~(tmp_6_fu_1165_p1 == 6'd34) & ~(tmp_6_fu_1165_p1 == 6'd33) & ~(tmp_6_fu_1165_p1 == 6'd32) & ~(tmp_6_fu_1165_p1 == 6'd31) & ~(tmp_6_fu_1165_p1 == 6'd30) & ~(tmp_6_fu_1165_p1 == 6'd29) & ~(tmp_6_fu_1165_p1 == 6'd28) & ~(tmp_6_fu_1165_p1 == 6'd27) & ~(tmp_6_fu_1165_p1 == 6'd26) & ~(tmp_6_fu_1165_p1 == 6'd25) & ~(tmp_6_fu_1165_p1 == 6'd24) & ~(tmp_6_fu_1165_p1 == 6'd23) & ~(tmp_6_fu_1165_p1 == 6'd22) & ~(tmp_6_fu_1165_p1 == 6'd21) & ~(tmp_6_fu_1165_p1 == 6'd20) & ~(tmp_6_fu_1165_p1 == 6'd19) & ~(tmp_6_fu_1165_p1 == 6'd18) & ~(tmp_6_fu_1165_p1 == 6'd17));
end

always @ (*) begin
    ap_condition_666 = ((1'b1 == ap_CS_fsm_state2) & (icmp_fu_1159_p2 == 1'd0) & (exitcond_fu_1137_p2 == 1'd0));
end

assign e_fu_2590_p2 = (d1_reg_738 + t0_fu_2507_p2);

assign exitcond_fu_1137_p2 = ((i_reg_713 == 7'd64) ? 1'b1 : 1'b0);

assign i_1_fu_1143_p2 = (i_reg_713 + 7'd1);

assign icmp_fu_1159_p2 = ((tmp_fu_1149_p4 == 3'd0) ? 1'b1 : 1'b0);

assign t0_fu_2507_p2 = (tmp17_reg_3058 + tmp16_fu_2503_p2);

assign tmp16_fu_2503_p2 = (tmp_30_reg_3048 + tmp_31_reg_3053);

assign tmp17_fu_2473_p2 = (tmp18_fu_2467_p2 + tmp_27_fu_2171_p2);

assign tmp18_fu_2467_p2 = (h1_reg_789 + tmp_32_fu_2333_p66);

assign tmp19_fu_2578_p2 = (tmp_38_fu_2548_p3 ^ tmp_35_fu_2526_p3);

assign tmp1_fu_1711_p2 = (tmp_17_fu_1571_p2 + W_load_1_phi_fu_1239_p66);

assign tmp20_fu_2596_p2 = (tmp_46_reg_3063 + t0_fu_2507_p2);

assign tmp2_fu_1717_p2 = (W_load_3_phi_fu_1577_p66 + tmp_9_fu_1233_p2);

assign tmp3_fu_2165_p2 = (tmp_23_fu_2135_p3 ^ tmp_20_fu_2113_p3);

assign tmp8_fu_1227_p2 = (tmp_7_fu_1205_p3 ^ tmp_11_fu_1223_p1);

assign tmp9_fu_1565_p2 = (tmp_22_fu_1561_p1 ^ tmp_15_fu_1543_p3);

assign tmp_10_fu_1507_p4 = {{W_load_2_phi_fu_1373_p66[31:7]}};

assign tmp_11_fu_1223_p1 = tmp_8_fu_1213_p4;

assign tmp_12_fu_1521_p3 = {{tmp_25_fu_1517_p1}, {tmp_10_fu_1507_p4}};

assign tmp_13_fu_1529_p4 = {{W_load_2_phi_fu_1373_p66[31:18]}};

assign tmp_14_fu_1179_p1 = ap_phi_mux_W_load_phi_phi_fu_805_p96[16:0];

assign tmp_15_fu_1543_p3 = {{tmp_34_fu_1539_p1}, {tmp_13_fu_1529_p4}};

assign tmp_16_fu_1551_p4 = {{W_load_2_phi_fu_1373_p66[31:3]}};

assign tmp_17_fu_1571_p2 = (tmp_12_fu_1521_p3 ^ tmp9_fu_1565_p2);

assign tmp_18_fu_2099_p4 = {{f_reg_751[31:6]}};

assign tmp_19_fu_1201_p1 = ap_phi_mux_W_load_phi_phi_fu_805_p96[18:0];

assign tmp_20_fu_2113_p3 = {{tmp_37_fu_2109_p1}, {tmp_18_fu_2099_p4}};

assign tmp_21_fu_2121_p4 = {{f_reg_751[31:11]}};

assign tmp_22_fu_1561_p1 = tmp_16_fu_1551_p4;

assign tmp_23_fu_2135_p3 = {{tmp_40_fu_2131_p1}, {tmp_21_fu_2121_p4}};

assign tmp_24_fu_2143_p4 = {{f_reg_751[31:25]}};

assign tmp_25_fu_1517_p1 = W_load_2_phi_fu_1373_p66[6:0];

assign tmp_26_fu_2157_p3 = {{tmp_47_fu_2153_p1}, {tmp_24_fu_2143_p4}};

assign tmp_27_fu_2171_p2 = (tmp_26_fu_2157_p3 ^ tmp3_fu_2165_p2);

assign tmp_28_fu_2177_p2 = (h_reg_776 ^ g_reg_763);

assign tmp_29_fu_2183_p2 = (tmp_28_fu_2177_p2 & f_reg_751);

assign tmp_2_fu_2087_p2 = (h1_reg_789 + 32'd1541459225);

assign tmp_30_fu_2189_p2 = (tmp_29_fu_2183_p2 ^ h_reg_776);

assign tmp_33_fu_2512_p4 = {{b_reg_700[31:2]}};

assign tmp_34_fu_1539_p1 = W_load_2_phi_fu_1373_p66[17:0];

assign tmp_35_fu_2526_p3 = {{tmp_49_fu_2522_p1}, {tmp_33_fu_2512_p4}};

assign tmp_36_fu_2534_p4 = {{b_reg_700[31:13]}};

assign tmp_37_fu_2109_p1 = f_reg_751[5:0];

assign tmp_38_fu_2548_p3 = {{tmp_50_fu_2544_p1}, {tmp_36_fu_2534_p4}};

assign tmp_39_fu_2556_p4 = {{b_reg_700[31:22]}};

assign tmp_3_fu_2003_p1 = i_reg_713[5:0];

assign tmp_40_fu_2131_p1 = f_reg_751[10:0];

assign tmp_41_fu_2570_p3 = {{tmp_51_fu_2566_p1}, {tmp_39_fu_2556_p4}};

assign tmp_42_fu_2584_p2 = (tmp_41_fu_2570_p3 ^ tmp19_fu_2578_p2);

assign tmp_43_fu_2479_p2 = (d_reg_725 | c_reg_688);

assign tmp_44_fu_2485_p2 = (tmp_43_fu_2479_p2 & b_reg_700);

assign tmp_45_fu_2491_p2 = (d_reg_725 & c_reg_688);

assign tmp_46_fu_2497_p2 = (tmp_45_fu_2491_p2 | tmp_44_fu_2485_p2);

assign tmp_47_fu_2153_p1 = f_reg_751[24:0];

assign tmp_48_fu_2195_p1 = i_reg_713[5:0];

assign tmp_49_fu_2522_p1 = b_reg_700[1:0];

assign tmp_4_fu_1183_p3 = {{tmp_14_fu_1179_p1}, {tmp_s_fu_1169_p4}};

assign tmp_50_fu_2544_p1 = b_reg_700[12:0];

assign tmp_51_fu_2566_p1 = b_reg_700[21:0];

assign tmp_5_fu_1191_p4 = {{ap_phi_mux_W_load_phi_phi_fu_805_p96[31:19]}};

assign tmp_6_fu_1165_p1 = i_reg_713[5:0];

assign tmp_7_fu_1205_p3 = {{tmp_19_fu_1201_p1}, {tmp_5_fu_1191_p4}};

assign tmp_8_fu_1213_p4 = {{ap_phi_mux_W_load_phi_phi_fu_805_p96[31:10]}};

assign tmp_9_fu_1233_p2 = (tmp_4_fu_1183_p3 ^ tmp8_fu_1227_p2);

assign tmp_fu_1149_p4 = {{i_reg_713[6:4]}};

assign tmp_s_fu_1169_p4 = {{ap_phi_mux_W_load_phi_phi_fu_805_p96[31:17]}};

endmodule //sha256_transform_16
